### ISSUE TITLE
Bug: cannot reply to direct_message messages

### ISSUE THREAD

**Issue by YannZeRookie** [brh55/botkit-discord#1]
Hello,

First of all, I'd like to tell you how much happy I was to find someone putting together BotKit and Discord. I am very excited!

I started playing with your code, and I think I spotted something fishy in `bot.js`, that makes the `bot.reply` method fail for messages of type `direct_message`. Consider this, from lines 27 to 36:

```
		if (src.type === 'direct_mention') {
			message.to = src.author.id;
		}

		if (
			src.type === 'mention' ||
			src.type === 'direct_mention'	
		) {
			message.to = src.channelId;
		}
```
I believe the second test of `src.type === 'direct_mention'` is wrong, and should be:

```
		if (
			src.type === 'mention' ||
			src.type === 'direct_message'	
		) {...
```
Otherwise you won't be able to reply to messages of type `direct_message`.

Do you welcome Pull Requests? Be advised that this is my first Node.js project - you have been warned ;)

Keep up the great work!

**Comment by brh55** [comment]
@YannZeRookie Ah, you are correct, actually it should be direct_message:

```js
		if (src.type === 'direct_message') {
			message.to = src.author.id;
		}
```

Feel free to submit pull requests, more than excited to accept your first Node related pull request. I'm slowly catching bugs and figuring out feature as I'm writing tutorials :).

**Comment by YannZeRookie** [comment]
Hi @brh55 

Thanks for your answer. Your correction is interesting, because it makes me wonder if your current implementation behaves as you expect, especially regarding the notion of "Direct Message".

Normally, in Discord's terminology, a Direct Message is a private message that you send to someone by opening a 1-to-1 channel with him. However, in the current implementation, if you code this:

```
discordBot.hears('hello','direct_message',(bot, message) => {
    bot.reply(message, 'Received a hello direct_message from ' + message.author.username);
});
```
You will actually catch any 'hello' message typed in **any** channel:

<img width="741" alt="image" src="https://user-images.githubusercontent.com/31187403/50524732-af7d9480-0ad7-11e9-9b60-59563643df85.png">

Now don't get me wrong: being able to scan ALL messages is GOOD. But I wonder if this is what you intended. If not, you'll want to fix it AND add a fourth type of messages (`message` maybe?), so that a bot can scan all messages. This is important.

Looking forward to hear from you,
-Yann

**Comment by YannZeRookie** [comment]
> it's probably best to keep it within the same terminology as Botkit as a `ambient`

Sounds great to me!

**Comment by brh55** [comment]
@YannZeRookie  Would you like to pull in a PR to apply these fixes?

**Comment by YannZeRookie** [comment]
Not sure I am good enough for this! I'm just starting with Node.js, and I am not familiar with BotKit. So that's asking a lot ;-) But I'd be happy to perform code reviewing - a great way to learn!

**Comment by brh55** [comment]
@YannZeRookie No problem! How about you send in a PR for the conditional fix at least :)

**Comment by YannZeRookie** [comment]
@brh55 I submitted my first PR - so proud ;)
