### ISSUE TITLE
BOT status

### ISSUE THREAD

**Issue by Dragon-tw** [brh55/botkit-discord#13]
How can i set my bot status?
Can I use (Bot.user.setStatus) and (Bot.user.setPresence) which are same as discord.js in botkit-discord ?

**Comment by ColdFiire** [comment]
I am wondering the same thing

**Comment by brh55** [comment]
Technically you should be able to access it through the `config.client` property of the controller instance.

ie:
```js
const discordBot = BotkitDiscord(config);
discordBot.config.client.user.setStatus();
```

But that was intentional, so I'm open to binding it to an alternative property, suggestions? (bot.client, bot.api?)
