### ISSUE TITLE
replies to itself

### ISSUE THREAD

**Issue by liminalitythree** [brh55/botkit-discord#14]
The bot replies to messages that it writes
example
```
const discordBot = BotkitDiscord(config);

discordBot.hears('hello','direct_message',(bot, message) => {
    bot.reply(message, 'hello');
});
```

if you write "hello" to it it will just say hello over and over.
also the receive middlewares also get called for messages the bot sends

**Comment by brh55** [comment]
Interesting, might be some changes to the Discord API. Shouldn't be the case

**Comment by YannZeRookie** [comment]
I have the same problem. Here is the line I insert at the beginning of each function:
```
    if (message.user.id == discordConfig.client.user.id) return; // Don't answer to ourselves
```
Not very elegant, but it works.

**Comment by Groovin-Dev** [comment]
https://github.com/brh55/botkit-discord/pull/20

**Comment by brh55** [comment]
merged and pushed to npm.
